force-app/main/default/objects/License__c/License__c.object-meta.xml
<CustomObject>
    <label>License</label>
    <nameField>
        <label>License Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/License__c/fields/Agent__c.field-meta.xml
<CustomField>
    <fullName>Agent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agent</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Licenses1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/License__c/fields/Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiry_Date__c</fullName>
    <label>Expiry Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/License__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>WB</fullName>
            </value>
            <value>
                <fullName>MH</fullName>
            </value>
            <value>
                <fullName>BH</fullName>
            </value>
            <value>
                <fullName>UP</fullName>
            </value>
            <value>
                <fullName>MP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Property__c/fields/Agent__c.field-meta.xml
<CustomField>
    <fullName>Agent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agent</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>WB</fullName>
            </value>
            <value>
                <fullName>MH</fullName>
            </value>
            <value>
                <fullName>BH</fullName>
            </value>
            <value>
                <fullName>MP</fullName>
            </value>
            <value>
                <fullName>UP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TriggerHelper.cls
public with sharing class TriggerHelper {

    public static void beforeInsert(List<Property__c> property_list){
        List<Property__c> property_list_withAgent = new List<Property__c>();
        for(Property__c p : property_list){                                 //adding all the properties with agent into a list
            if(p.Agent__c != null) property_list_withAgent.add(p);
        }
        validateAgentLicense(property_list_withAgent);
    }





    public static void validateAgentLicense(List<Property__c> p_list){
        Map<String,License__c> agent_licenseMap = new Map<String,License__c>();  
        Set<Id> agentId_set = new Set<Id>();
        Set<String> state_set = new Set<String>();
        for(Property__c p : p_list){
            agentId_set.add(p.Agent__c);
            state_set.add(p.State__c);
        }
        // now I have two set of AgentId and StateId , we have to query if we have such in license table whose expiration date is > Today
        List<License__c> license_list = [SELECT Agent__c , State__c FROM License__c WHERE Agent__c IN : agentId_set AND State__c IN : state_set AND Expiry_Date__c > Today];
        //storing all the agentId+stateId+exporyDate>today wala licenses in a map
        for(License__c l : license_list){
            agent_licenseMap.put(l.Agent__c+'-'+l.State__c,l);
        }
        //when I am unable to get such a key , will throw a error

        for(Property__c p : p_list){
            if(!agent_licenseMap.ContainsKey(p.Agent__c+'-'+p.State__c)){
                p.addError('No such License');
            }
        }
    }



    public TriggerHelper() {

    }
}